### PR TITLE
Anomaly detector detection re running in inspect mode #757

### LINKED ISSUE #757: Anomaly detector: detection re-running in inspect mode
Steps to reproduce:
- create `Anomaly` analytic unit
- `Apply`
- enable `Inspect mode`

Behavior:
- analytic unit status jumps from `LEARNING` to `DETECTION` infinitely

Expected behavior:
- analytic unit status is `READY`, detections and HSR are displayed

### PR DESCRIPTION
**Pull request by amper43**
fixes #757 

## Problem
`getHSR` method runs learning if cache of analytic unit is `null` or outdated. Panel requests HSR every second and creates a race condition between learning process and HSR requests.
Note: cache can't be outdated because learning started on each unit's update if it required in class definition.

## Changes
- don't return response with HSR if analytic unit in `LEARNING` state
- remove unused method `isCacheOutdated`

### CODE REVIEW

File: server/src/controllers/analytics_controller.ts [hunk 1]
```diff
@@ -644,7 +644,7 @@ export async function getHSR(
   hsr: TableTimeSeries,
```
Comment (jonyrock) [inline server/src/controllers/analytics_controller.ts]: let's make a class for this

File: server/src/controllers/analytics_controller.ts [hunk 2]
```diff
@@ -657,7 +657,11 @@ export async function getHSR(
     }
 
     let cache = await AnalyticUnitCache.findById(analyticUnit.id);
-    if(cache === null || cache.isCacheOutdated(analyticUnit)) {
+
+    if(cache === null || cache.data === null) {
```
Comment (jonyrock) [inline server/src/controllers/analytics_controller.ts]: please explain when `cache.data === null`

File: server/src/controllers/analytics_controller.ts [hunk 3]
```diff
@@ -657,7 +657,11 @@ export async function getHSR(
...
+      if(analyticUnit.status === AnalyticUnit.AnalyticUnitStatus.LEARNING) {
+        return; //because we wait end of learning
```
Comment (jonyrock) [inline server/src/controllers/analytics_controller.ts]:
```suggestion
        return; // because we wait end of learning
```

File: server/src/controllers/analytics_controller.ts (hunk 2 above)
Comment (amper43) [reply server/src/controllers/analytics_controller.ts]: when learning started but not completed yet or first learning was failed.

File: server/src/controllers/analytics_controller.ts (hunk 1 above)
Comment (amper43) [reply server/src/controllers/analytics_controller.ts]: according TODOs we should make it in data-kit
related issue https://github.com/CorpGlory/grafana-datasource-kit/issues/89

File: server/src/controllers/analytics_controller.ts (hunk 2 above)
Comment (jonyrock) [reply server/src/controllers/analytics_controller.ts]: please add a comment about this into the code

File: server/spec/analytic_controller.jest.ts [hunk 4]
```diff
@@ -136,3 +134,12 @@ describe('onDetect', () => {
     expect(detectedRanges).toEqual([[7, 8]]);
   });
 });
+
+describe('getHSR', function() {
+  it('should return nothink if unit state is LEARNING', async () => {
```
Comment (rozetko) [inline server/spec/analytic_controller.jest.ts]:
```suggestion
  it('should return nothing if unit state is LEARNING', async () => {
```

File: server/spec/analytic_controller.jest.ts [hunk 5]
```diff
@@ -136,3 +134,12 @@ describe('onDetect', () => {
...
+    const analyticUnitId = await addTestUnitToDB()
+    const unit = await AnalyticUnit.findById(analyticUnitId);
+    const result = await getHSR(unit, 9000, 100000);
+    expect(result.hsr).toBe(undefined);
+  });
+});
```
Comment (rozetko) [inline server/spec/analytic_controller.jest.ts]:
```suggestion
});

```

File: server/spec/analytic_controller.jest.ts [hunk 6]
```diff
@@ -136,3 +134,12 @@ describe('onDetect', () => {
     expect(detectedRanges).toEqual([[7, 8]]);
   });
 });
+
+describe('getHSR', function() {
+  it('should return nothink if unit state is LEARNING', async () => {
+    const analyticUnitId = await addTestUnitToDB()
+    const unit = await AnalyticUnit.findById(analyticUnitId);
+    const result = await getHSR(unit, 9000, 100000);
+    expect(result.hsr).toBe(undefined);
```
Comment (rozetko) [inline server/spec/analytic_controller.jest.ts]: does panel work as expected with `undefined` hsr?

File: server/spec/analytic_controller.jest.ts [hunk 7]
```diff
@@ -16,71 +16,69 @@ import { buildSegments, clearSegmentsDB, convertSegmentsToTimeRanges } from './u
...
+  createdAt: {"$$date":1564476040880},
+  updatedAt: {"$$date":1564476040880}
+}
+
+const WINDOW_SIZE = 10;
+const TIME_STEP = 1000;
+
+async function addTestUnitToDB(): Promise<string> {
+  const analyticUnitId = await saveAnalyticUnitFromObject(analyticUnitObj);
+  await AnalyticUnit.update(analyticUnitId, {lastDetectionTime: 1000});
```
Comment (jonyrock) [inline server/spec/analytic_controller.jest.ts]:
```suggestion
  await AnalyticUnit.update(analyticUnitId, { lastDetectionTime: 1000 });
```

File: server/spec/analytic_controller.jest.ts [hunk 8]
```diff
@@ -3,90 +3,91 @@ import { queryByMetric } from 'grafana-datasource-kit';
...
-        url: "api/datasources/proxy/5/query",
-        method: "GET",
-        data: null,
-        params: {
-          db:"dbname",
-          q: "SELECT mean(\"value\") FROM \"autogen\".\"tcpconns_value\" WHERE time >= now() - 6h GROUP BY time(20s) fill(null)",
-          epoch: "ms"
-        },
-        type: "influxdb"
+import * as _ from 'lodash';
```
Comment (jonyrock) [inline server/spec/analytic_controller.jest.ts]:
```suggestion
import * as _ from 'lodash';

```

File: server/spec/analytic_controller.jest.ts [hunk 9]
```diff
@@ -3,90 +3,91 @@ import { queryByMetric } from 'grafana-datasource-kit';
 jest.mock('grafana-datasource-kit', () => (
   {
     ...(jest.requireActual('grafana-datasource-kit')),
-    queryByMetric: jest.fn((metric, url, from, to, apiKey) => {})
+    queryByMetric: jest.fn((metric, url, from, to, apiKey) => {
+      return {values:[], columns:[]}
```
Comment (jonyrock) [inline server/spec/analytic_controller.jest.ts]:
```suggestion
      return { values:[], columns:[] }
```

File: server/src/controllers/analytics_controller.ts [hunk 10]
```diff
@@ -644,26 +644,31 @@ export async function getHSR(
...
   upperBound?: TableTimeSeries
-}> {
+} | undefined> {
   try {
+
     const grafanaUrl = getGrafanaUrl(analyticUnit.grafanaUrl);
-    const data = await queryByMetric(analyticUnit.metric, grafanaUrl, from, to, HASTIC_API_KEY);
     let resultSeries: HSRResult = {
-      hsr: data
+      hsr: undefined
```
Comment (jonyrock) [inline server/src/controllers/analytics_controller.ts]: HSR defined that `hsr` is NOT optional. So please don't lie to others and force undefined here. 
You may make this field optional in `HSRResult` definition

File: server/spec/analytic_controller.jest.ts (hunk 6 above)
Comment (amper43) [reply server/spec/analytic_controller.jest.ts]: yes

File: server/src/controllers/analytics_controller.ts [hunk 11]
```diff
@@ -640,34 +640,39 @@ export async function getHSR(
...
 
     let cache = await AnalyticUnitCache.findById(analyticUnit.id);
-    if(cache === null || cache.isCacheOutdated(analyticUnit)) {
-      await runLearning(analyticUnit.id, from, to);
-      cache = await AnalyticUnitCache.findById(analyticUnit.id);
+
+    const inLearningState = analyticUnit.status === AnalyticUnit.AnalyticUnitStatus.LEARNING;
+
+    //cache.data === null when learning started but not completed yet or first learning was failed
+    if(cache === null || cache.data === null || inLearningState) {
```
Comment (rozetko) [inline server/src/controllers/analytics_controller.ts]: maybe `inLearningState` should be the first condition?
existing cache might be not actual if analytic unit is in learning state
