### PR TITLE
Error: Can`t find cache for analytic unit #772

### LINKED ISSUE #772: Error: Can`t find cache for analytic unit
If you create Analytic Unit with Detector Type Pattern and label any segment, there will be an Error:
```
Error: Can`t find cache for analytic unit G3uWBXaIoQ2A4YY2
    at Object.<anonymous> (/mnt/c/Users/VargB/git/hastic-server/server/dist/server-dev.js:2144:19)
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/c/Users/VargB/git/hastic-server/server/dist/server-dev.js:2000:32)
    at <anonymous>
```
image

### PR DESCRIPTION
**Pull request by VargBurz**
Closes #772 

Missing cache for "Pattern" analytic unit leads to `Can't find cache for analytic unit` exception in `mergeAndInsertSegments`. `mergeAndInsertSegments` doesn't use cache when "Pattern" detector is used.

## Changes

- remove throwing exception
- add default `intersectionRangeExtension` value for non-pattern detectors: 0. If cache is not `null`, `intersectionRangeExtension` is taken from cache.

### CODE REVIEW

File: server/src/models/segment_model.ts [hunk 1]
```diff
@@ -180,10 +176,16 @@ export async function mergeAndInsertSegments(segments: Segment[]): Promise<{
         deleted: segment.deleted
       });
     } else {
-      const timeStep = cache.getTimeStep();
+      let intersectionRange = 0;
```
Comment (rozetko) [inline server/src/models/segment_model.ts]: Let's rename it to `intersectionRangeExtension`

File: server/src/models/analytic_unit_cache_model.ts [hunk 2]
```diff
@@ -49,8 +49,11 @@ export class AnalyticUnitCache {
     return 3 * MILLISECONDS_IN_INDEX;
   }
 
-  public getTimeStep(): number {
-    return this.data.timeStep;
+  public getTimeStep(): number | undefined {
```
Comment (jonyrock) [inline server/src/models/analytic_unit_cache_model.ts]:
```suggestion
  public get timeStep(): number | undefined {
```
