### PR TITLE
Error cannot read property data of null #739

### LINKED ISSUE #739: Error: Cannot read property 'data' of null
We should check that `data` is not `null` here
https://github.com/hastic/hastic-server/blob/master/server/src/models/analytic_unit_cache_model.ts#L36

`data` contains cache, it is a responce from DB
Data will be null if analytic unit hasn't got though "learning" stage

### PR DESCRIPTION
**Pull request by amper43**
fixes #739 

## Problem

in `getIntersection` there isn't a check that `this.data` is null. Data will be null when analytic unit haven't got though "learning" stage. It happens when user creates an analytic unit and goes to inspect mode.

## Changes
- added check for `cache.data` === `null` case
- `getHSR`: check threshold's fields for case when threshold needs learning

### CODE REVIEW

**Comment by jonyrock** [comment]
> null `this.data` case? 

Sorry, I don't understand. Please explain which case

**Comment by amper43** [comment]
> > null `this.data` case?
> 
> Sorry, I don't understand. Please explain which case

description updated

File: server/src/controllers/analytics_controller.ts [hunk 1]
```diff
@@ -659,9 +659,17 @@ export async function getHSR(
 
     let cache = await AnalyticUnitCache.findById(analyticUnit.id);
     if(
-      cache === null ||
-      cache.data.alpha !== (analyticUnit as AnalyticUnit.AnomalyAnalyticUnit).alpha ||
-      cache.data.confidence !== (analyticUnit as AnalyticUnit.AnomalyAnalyticUnit).confidence
+        cache === null ||
```
Comment (jonyrock) [inline server/src/controllers/analytics_controller.ts]: it is the biggest `if` statement I saw in my entire software engineering career. 

Please make a function for this.

File: server/src/models/analytic_unit_cache_model.ts [hunk 2]
```diff
@@ -33,7 +33,7 @@ export class AnalyticUnitCache {
   }
 
   public getIntersection(): number {
-    if(this.data.windowSize !== undefined) {
+    if(this.data !== null && this.data.windowSize !== undefined) {
```
Comment (jonyrock) [inline server/src/models/analytic_unit_cache_model.ts]: can `this.data` be `undefined`?   
```
undefined !== null // true
```

File: server/src/controllers/analytics_controller.ts [hunk 3]
```diff
@@ -658,11 +658,8 @@ export async function getHSR(
     }
 
     let cache = await AnalyticUnitCache.findById(analyticUnit.id);
-    if(
-      cache === null ||
-      cache.data.alpha !== (analyticUnit as AnalyticUnit.AnomalyAnalyticUnit).alpha ||
-      cache.data.confidence !== (analyticUnit as AnalyticUnit.AnomalyAnalyticUnit).confidence
-    ) {
+    const analyticFields = analyticUnit.getAnalyticFields();
+    if(cache === null || !_.every(_.keys(analyticFields).map(k => analyticFields[k] === cache.data[k]))) {
```
Comment (jonyrock) [inline server/src/controllers/analytics_controller.ts]:
```suggestion
    let someSemanticVarName = _.every(_.keys(analyticFields).map(k => analyticFields[k] === cache.data[k]));
    if(cache === null || !someMeamingfullVariableName) {
```

Comment (jonyrock) [reply server/src/controllers/analytics_controller.ts]: I see that you use `cache.data[k]` in `someSemanticVarName`
Well, you better write a bool function which resolves what you want. So it's better
```js
analyticUnitFieldsEqualsToCache(analyticUnit: AnalyticUnit, cache?: CacheModel): boolean {
  if(cache === null) {
    return false;
  }
  // it's better to use https://lodash.com/docs/4.17.15#isEqual here
  var analyticFields = analyticUnit.getAnalyticFields();
  return _.every(_.keys(analyticFields).map(k => analyticFields[k] === cache.data[k])
}
```

File: server/src/models/analytic_units/analytic_unit_model.ts [hunk 4]
```diff
@@ -78,4 +77,6 @@ export abstract class AnalyticUnit {
     };
   }
 
+  public getAnalyticFields(): any {};
```
Comment (jonyrock) [inline server/src/models/analytic_units/analytic_unit_model.ts]: just `any` , what if `any[]` ?
