### PR TITLE
Keyerror pattern model #471

### LINKED ISSUE #471: KeyError: 'pattern_model'
```
  File "C:\Users\VargB\git\hastic-server\analytics\bin\..\analytics\analytic_unit_manager.py", line 94, in handle_analytic_task
    result_payload = await self.__handle_analytic_task(task)
  File "C:\Users\VargB\git\hastic-server\analytics\bin\..\analytics\analytic_unit_manager.py", line 88, in __handle_analytic_task
    return await worker.do_detect(data, payload['cache'])
  File "C:\Users\VargB\git\hastic-server\analytics\bin\..\analytics\analytic_unit_worker.py", line 34, in do_detect
    return self._detector.detect(data, cache)
  File "C:\Users\VargB\git\hastic-server\analytics\bin\..\analytics\detectors\pattern_detector.py", line 53, in detect
    detected = self.model.detect(dataframe, cache)
  File "C:\Users\VargB\git\hastic-server\analytics\bin\..\analytics\models\model.py", line 93, in detect
    result = self.do_detect(dataframe)
  File "C:\Users\VargB\git\hastic-server\analytics\bin\..\analytics\models\general_model.py", line 68, in do_detect
    pat_data = self.state['pattern_model']
KeyError: 'pattern_model'
```

Step to reproduce:
Create about 10 analytic units, enable all webhooks.
There will be KeyError in analytics logs

### PR DESCRIPTION
**Pull request by VargBurz**
Closes #471 

Analytics can get a webhook with empty cache, it leads to errors. Added checks for empty cache for easier debugging process.

### CODE REVIEW

**Comment by jonyrock** [comment]
@VargBurz please explain the fix

File: server/src/services/data_puller.ts [hunk 1]
```diff
@@ -82,7 +82,9 @@ export class DataPuller {
       throw Error(`data puller can't push unit: ${unit} data: ${data}`);
     }
     let task = new AnalyticsTask(unit.id, AnalyticsTaskType.PUSH, data);
-
+    if (data.cache.length == 0) {
```
Comment (rozetko) [inline server/src/services/data_puller.ts]: You're checking for an empty array here
But it could be an empty object or `null`
```suggestion
    if(_.isEmpty(data.cache) || data.cache === null) {
```

File: server/src/services/data_puller.ts [hunk 2]
```diff
@@ -82,7 +82,9 @@ export class DataPuller {
       throw Error(`data puller can't push unit: ${unit} data: ${data}`);
     }
     let task = new AnalyticsTask(unit.id, AnalyticsTaskType.PUSH, data);
-
+    if (data.cache === null || _.isEmpty(data.cache)) {
```
Comment (rozetko) [inline server/src/services/data_puller.ts]:
```suggestion
    if(_.isEmpty(data.cache)) {
```

File: analytics/analytics/detectors/pattern_detector.py [hunk 3]
```diff
@@ -43,6 +43,8 @@ def __init__(self, pattern_type: str, analytic_unit_id: AnalyticUnitId):
     def train(self, dataframe: pd.DataFrame, segments: list, cache: Optional[models.ModelCache]) -> models.ModelCache:
         # TODO: pass only part of dataframe that has segments
         new_cache = self.model.fit(dataframe, segments, cache)
+        if not new_cache:
```
Comment (rozetko) [inline analytics/analytics/detectors/pattern_detector.py]: Maybe `if new_cache == None`?
