### PR TITLE
Threshold value is not saving #368

### LINKED ISSUE #368: Threshold value is not saving
Steps to reproduce:

* create threshold analytic unit
* change value
* save dashboard
* refresh

Value would stay default

### PR DESCRIPTION
**Pull request by amper43**
fixes #368

### CODE REVIEW

File: server/src/models/threshold_model.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export class Threshold {
 }
 
 export async function findOne(id: AnalyticUnitId): Promise<Threshold | null> {
-  const query: any = { id };
+  const query: any = { _id: id };
```
Comment (jonyrock) [inline server/src/models/threshold_model.ts]:
```suggestion
  const query = { _id: id };
```

Comment (jonyrock) [reply server/src/models/threshold_model.ts]: you can use https://github.com/hastic/hastic-server/blob/master/server/src/services/data_service.ts#L39

File: server/src/models/threshold_model.ts [hunk 2]
```diff
@@ -61,9 +61,9 @@ export async function findOne(id: AnalyticUnitId): Promise<Threshold | null> {
 export async function updateThreshold(id: AnalyticUnitId, value: number, condition: Condition) {
   const threshold = await db.findOne(id);
   if(threshold === null) {
-    return db.insertOne({ id, value, condition });
+    return db.insertOne({ _id: id, value, condition });
   }
-  return db.updateOne({ id }, { value, condition });
+  return db.updateOne({ _id: id }, { value, condition });
```
Comment (jonyrock) [inline server/src/models/threshold_model.ts]:
```suggestion
  return db.updateOne(id, { value, condition });
```
