### PR TITLE
Thresholds error: from is NaN #621

### LINKED ISSUE #621: Thresholds error: from is NaN
You get this error any time you click `Apply` on threshold analytic unit
image
There was no error before implementing https://github.com/hastic/hastic-server/issues/504

### PR DESCRIPTION
**Pull request by rozetko**
Fixes #621 

The error occurred because of missing `windowSize` field in Threshold`s detection cache 

Changes:
- use `from` and `to` in learning and detection if they're provided 
- check if `cache` has `windowSize`
- remove previously found segments before learning

### CODE REVIEW

File: server/src/controllers/analytics_controller.ts [hunk 1]
```diff
@@ -232,7 +232,12 @@ export async function runLearning(id: AnalyticUnit.AnalyticUnitId) {
       };
     }
 
-    const range = await getQueryRange(id, detector);
+    let range;
```
Comment (jonyrock) [inline server/src/controllers/analytics_controller.ts]: can we define TimeRange type somewhere in the code, please?

Comment (jonyrock) [reply server/src/controllers/analytics_controller.ts]: it's cuz u call `query(analyticUnit, range)` and technically, u don't define `range` type for this variable.
