### PR TITLE
Failed node.js test: no .git folder #314

### LINKED ISSUE #314: Failed node.js test: no .git folder
More info: https://travis-ci.org/hastic/hastic-server/jobs/466150072

I think we should rethink how we test .git folder and what environment necessary for testing

### PR DESCRIPTION
**Pull request by rozetko**
Fixes #314 

- Check for branch-file to exist
- Create mock for `config.ts`

image

image

### CODE REVIEW

File: server/src/config.ts [hunk 1]
```diff
@@ -72,13 +72,18 @@ function getGitInfo() {
...
-  const rev = fs.readFileSync(gitHeadFile).toString();
-  let branchPath = rev.indexOf(':') === -1 ? rev : rev.slice(5, -1);
+  const ref = fs.readFileSync(gitHeadFile).toString();
+  let branchPath = ref.indexOf(':') === -1 ? ref : ref.slice(5, -1);
   let branch = branchPath.split('/').pop();
-  let commitHash = fs.readFileSync(`${gitRoot}/${branchPath}`).toString().slice(0, 7);
+  const branchFilename = `${gitRoot}/${branchPath}`;
+  if(!fs.existsSync(branchFilename)) {
+    console.error(`Can't find git branch file ${branchFilename}`);
+    return null;
```
Comment (amper43) [inline server/src/config.ts]: maybe we should return empty str?

Comment (jonyrock) [reply server/src/config.ts]: `null` is fine
